# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ageing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Account', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='ageing',
            name='TotalAR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Worklist'),
        ),
    ]
