# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='financials_2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_ID', models.CharField(max_length=255)),
                ('entity_or_parent', models.CharField(max_length=255)),
                ('Total_Assets', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
