# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials_2015',
            name='Total_Assets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
