# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_ageing_age60'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ageing',
            name='Age60',
        ),
    ]
