# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20170809_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='financials_2015',
            new_name='Financials2015',
        ),
    ]
