# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_remove_ageing_age60'),
    ]

    operations = [
        migrations.CreateModel(
            name='financials_2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_ID', models.CharField(max_length=250)),
                ('entity_or_parent', models.CharField(max_length=250)),
                ('Total_Assets', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='ageing',
            name='TotalAR',
        ),
        migrations.DeleteModel(
            name='Ageing',
        ),
        migrations.DeleteModel(
            name='Worklist',
        ),
    ]
