# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20170731_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='financials_2014',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_ID', models.CharField(max_length=250)),
                ('entity_or_parent', models.CharField(max_length=250)),
                ('Total_Assets', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
