# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_financials_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='financials_2014',
        ),
    ]
